linters-settings:
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - misspell
    - gocyclo
    - dupl
    - goconst
    - gofmt
    - gosec

  disable:
    - maligned

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl

run:
  timeout: 5m